"use client";

import { motion } from "framer-motion";
import {
  Dumbbell, Utensils, ListChecks, Timer, TrendingUp, Bot, Users, Trophy,
  Settings, CreditCard, Building2, BarChart3, Heart, Zap, Smartphone,
  Shield, Globe, Flame, Camera, Salad, CalendarDays, Target, Sparkles,
} from "lucide-react";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { FitxCard } from "@/components/ui/FitxCard";
import { FitxButton } from "@/components/ui/FitxButton";
import { CTASection } from "@/components/marketing/CTASection";
import Link from "next/link";

const modules = [
  {
    id: "exercises",
    icon: Dumbbell,
    title: "Complete Exercise Library",
    subtitle: "5,000+ exercises with video demos",
    description:
      "The most comprehensive exercise database available. Every exercise includes HD video demonstrations, step-by-step instructions, pro tips, common mistakes, and interactive muscle maps showing exactly which muscles are activated.",
    features: [
      "HD video demos for every exercise",
      "Front/back body SVG muscle activation maps",
      "Smart filtering by muscle, equipment, difficulty",
      "Personal history and PR tracking per exercise",
      "Alternative exercise suggestions",
      "Voice search and instant search",
    ],
  },
  {
    id: "nutrition",
    icon: Utensils,
    title: "Diet & Nutrition System",
    subtitle: "Complete macro tracking with AI",
    description:
      "Track every meal with our smart nutrition system. Scan barcodes, snap photos of your food for AI recognition, and get personalized meal plans generated by AI based on your goals.",
    features: [
      "Barcode scanner with 15M+ food database",
      "AI food photo recognition via GPT-4 Vision",
      "Animated macro rings (Calories/Protein/Carbs/Fat)",
      "Weekly meal planner with AI generation",
      "Recipe library with adjustable servings",
      "Diet modes: Bulking / Cutting / Maintenance / Performance",
    ],
  },
  {
    id: "tasks",
    icon: ListChecks,
    title: "Task Manager & Habits",
    subtitle: "Fitness-aware productivity",
    description:
      "The first task manager designed specifically for fitness. Link tasks to workouts and meals, track habits with streaks, and get smart AI suggestions to stay consistent.",
    features: [
      "Priority levels with color coding",
      "Recurring tasks with custom patterns",
      "Habit tracking with streak flames",
      "Calendar view with category dots",
      "Link tasks to workouts and meals",
      "AI suggestions based on your patterns",
    ],
  },
  {
    id: "workout",
    icon: Timer,
    title: "Workout Engine",
    subtitle: "Full immersive workout tracking",
    description:
      "The most powerful workout tracker ever built. Real-time set logging, animated rest timers, plate calculators, RPE tracking, and automatic PR detection with celebrations.",
    features: [
      "Active workout with live set tracking",
      "Animated countdown rest timer",
      "Plate calculator for any bar weight",
      "1RM estimator from working sets",
      "Auto-save every 30 seconds",
      "Confetti + fire celebration on PRs",
    ],
  },
  {
    id: "progress",
    icon: TrendingUp,
    title: "Progress & Analytics",
    subtitle: "Data-driven insights",
    description:
      "Visualize your transformation with powerful charts, progress photo comparisons, muscle volume heatmaps, and personal record boards. Every metric, beautifully presented.",
    features: [
      "Weight-over-time progression charts",
      "Body measurement tracking",
      "Progress photo timeline with comparison slider",
      "Muscle volume heatmap (front + back body)",
      "Push/pull/leg balance detection",
      "Personal records board with share cards",
    ],
  },
  {
    id: "ai-coach",
    icon: Bot,
    title: "AI Coach",
    subtitle: "GPT-4 powered personal trainer",
    description:
      "Your 24/7 AI fitness coach that knows everything about your workouts, nutrition, recovery, and goals. Ask anything — it gives personalized, context-aware advice.",
    features: [
      "Powered by GPT-4 with full context",
      "Knows your workouts, meals, and body data",
      "Can generate custom workouts on the fly",
      "Answers: 'Why am I not losing weight?'",
      "Voice input support",
      "Proactive daily insights and suggestions",
    ],
  },
  {
    id: "social",
    icon: Users,
    title: "Social & Community",
    subtitle: "Train together, grow together",
    description:
      "Share your journey with a community of athletes. Post workout recaps, celebrate PRs, join group challenges, and compete on leaderboards with friends.",
    features: [
      "Activity feed with workout posts",
      "Reactions and comments",
      "Global and friends leaderboards",
      "Group fitness challenges",
      "User profiles with XP and stats",
      "Direct messaging",
    ],
  },
  {
    id: "gamification",
    icon: Trophy,
    title: "Gamification System",
    subtitle: "Level up your fitness",
    description:
      "Turn your fitness journey into an RPG. Earn XP for every workout, meal logged, and habit completed. Unlock 200+ achievement badges and climb through 50 levels.",
    features: [
      "XP for every action (workouts, meals, tasks)",
      "50 levels: Rookie to Immortal",
      "200+ achievement badges with rarity tiers",
      "Full-screen level-up celebrations",
      "Streak multipliers",
      "Hexagonal badge collection with glow effects",
    ],
  },
  {
    id: "toggles",
    icon: Settings,
    title: "Toggle Mode System",
    subtitle: "Customize everything",
    description:
      "Every aspect of FITX adapts to your preferences instantly. Switch between dark/light mode, metric/imperial, gym/home workouts, and diet modes with a single tap.",
    features: [
      "Dark / Light theme",
      "Metric (kg/cm) / Imperial (lbs/ft)",
      "Gym / Home / Outdoor workout mode",
      "Bulking / Cutting / Maintenance diet",
      "Beginner / Intermediate / Advanced",
      "Per-category notification controls",
    ],
  },
  {
    id: "gym-admin",
    icon: Building2,
    title: "Gym Admin Dashboard",
    subtitle: "Run your entire gym from one platform",
    description:
      "The complete gym management solution. Track members, revenue, classes, and trainers. White-label the entire platform with your gym's logo and colors.",
    features: [
      "Member management with search and filters",
      "Revenue dashboard with MRR charts",
      "Class scheduling and booking",
      "Trainer and coach management",
      "Retention and compliance analytics",
      "White-label branding controls",
    ],
  },
];

export default function FeaturesPage() {
  return (
    <div className="pt-24">
      <section className="py-16 text-center">
        <div className="max-w-4xl mx-auto px-4">
          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-5xl md:text-7xl font-display tracking-wider text-fitx-text uppercase mb-4"
          >
            Every Feature You <span className="text-gradient-red">Need</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="text-lg text-fitx-text-secondary font-body max-w-2xl mx-auto"
          >
            Deep dive into the 10+ modules that make FITX the most complete fitness platform ever built.
          </motion.p>
        </div>
      </section>

      {modules.map((mod, i) => (
        <section
          key={mod.id}
          id={mod.id}
          className={`py-20 ${i % 2 === 0 ? "bg-background" : "bg-fitx-surface"}`}
        >
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className={`flex flex-col lg:flex-row items-center gap-12 ${i % 2 !== 0 ? "lg:flex-row-reverse" : ""}`}>
              <motion.div
                initial={{ opacity: 0, x: i % 2 === 0 ? -40 : 40 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6 }}
                className="flex-1"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-12 h-12 rounded-xl bg-fitx-primary/10 border border-fitx-primary/20 flex items-center justify-center">
                    <mod.icon className="h-6 w-6 text-fitx-primary" />
                  </div>
                  <div>
                    <h2 className="text-2xl md:text-3xl font-display tracking-wider text-fitx-text uppercase">
                      {mod.title}
                    </h2>
                    <p className="text-sm text-fitx-text-secondary font-heading uppercase tracking-wider">
                      {mod.subtitle}
                    </p>
                  </div>
                </div>
                <p className="text-fitx-text-secondary font-body leading-relaxed mb-8">
                  {mod.description}
                </p>
                <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {mod.features.map((feat) => (
                    <li key={feat} className="flex items-start gap-2 text-sm text-fitx-text-secondary font-body">
                      <Sparkles size={14} className="text-fitx-primary flex-shrink-0 mt-1" />
                      {feat}
                    </li>
                  ))}
                </ul>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, x: i % 2 === 0 ? 40 : -40 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: 0.2 }}
                className="flex-1"
              >
                <div className="relative aspect-[4/3] rounded-2xl bg-fitx-card border border-fitx-border overflow-hidden flex items-center justify-center">
                  <div className="absolute inset-0 bg-gradient-to-br from-fitx-primary/5 to-transparent" />
                  <mod.icon className="h-24 w-24 text-fitx-primary/20" />
                  <div className="absolute bottom-4 left-4 right-4 bg-fitx-surface/80 backdrop-blur-sm rounded-xl p-4 border border-fitx-border">
                    <p className="text-xs font-heading text-fitx-text-secondary uppercase tracking-wider">
                      {mod.subtitle}
                    </p>
                    <div className="flex gap-2 mt-2">
                      {mod.features.slice(0, 3).map((f, j) => (
                        <span key={j} className="text-[10px] bg-fitx-primary/10 text-fitx-primary px-2 py-1 rounded-full font-mono">
                          {f.split(" ").slice(0, 3).join(" ")}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              </motion.div>
            </div>
          </div>
        </section>
      ))}

      <CTASection />
    </div>
  );
}
